name: MCSR
description: MCSR Unofficial
author: DaytonJWatson
version: 0.0.1
api-version: '1.16'
main: com.daytonjwatson.mcsr.MCSR
commands:
  debug:
  generatehub:
    description: Generate the hub world
    usage: /generatehub
  spawn:
    description: Teleport to spawn
    usage: /spawn
  setspawn:
    description: Set the server spawn
    usage: /setspawn
    permission: mcsr.setspawn
  startrun:
  stoprun:
  forfeit:
  playerdata:
    description: View player run data
    usage: /playerdata [player] [chat]
  leaderboard:
    description: View the server leaderboard
    usage: /leaderboard
